In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [12]:
train_df = pd.read_csv("dataSet/a01c26dcd27711ea/Dataset/train.csv")
test_df = pd.read_csv("dataSet/a01c26dcd27711ea/Dataset/test.csv")

In [13]:

colorType_df = pd.get_dummies(train_df.color_type, prefix='color_type')
train_df

,color_type_Agouti,color_type_Apricot,color_type_Black,color_type_Black Brindle,color_type_Black Smoke,color_type_Black Tabby,color_type_Black Tiger,color_type_Blue,color_type_Blue Cream,color_type_Blue Merle,...,color_type_Silver Lynx Point,color_type_Silver Tabby,color_type_Tan,color_type_Torbie,color_type_Tortie,color_type_Tortie Point,color_type_Tricolor,color_type_White,color_type_Yellow,color_type_Yellow Brindle
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18830,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18832,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X = train_df.drop(['breed_category', 'pet_category'], axis=1)
y_breedcateory = train_df['breed_category']
y_petcateory = train_df['pet_category']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y_breedcateory, test_size=0.33, random_state=42)

In [10]:
X_train

,pet_id,issue_date,listing_date,condition,color_type,length(m),height(cm),X1,X2
10638,ANSL_58528,2016-07-11 00:00:00,2016-10-08 17:36:00,1.0,White,0.34,26.98,0,1
2171,ANSL_51427,2010-02-03 00:00:00,2019-03-11 12:25:00,1.0,Tricolor,0.14,41.35,13,9
14209,ANSL_71529,2014-08-14 00:00:00,2016-09-11 14:29:00,2.0,Red,0.08,28.95,0,7
3604,ANSL_61455,2010-04-20 00:00:00,2017-05-11 12:34:00,1.0,Brown Brindle,0.18,27.89,0,7
14233,ANSL_63730,2009-08-20 00:00:00,2017-09-13 17:35:00,2.0,Tricolor,0.09,41.21,13,9
...,...,...,...,...,...,...,...,...,...
11284,ANSL_50486,2016-10-23 00:00:00,2017-01-11 11:50:00,2.0,Black,0.71,19.36,13,9
11964,ANSL_50827,2014-07-01 00:00:00,2018-03-23 16:01:00,1.0,Brown,0.89,5.48,0,7
5390,ANSL_61235,2018-03-16 00:00:00,2019-01-18 14:27:00,0.0,Buff,0.57,41.61,0,1
860,ANSL_60611,2018-07-14 00:00:00,2018-10-29 13:22:00,0.0,Black,0.83,14.00,7,1
15795,ANSL_66688,2016-10-14 00:00:00,2017-11-20 18:43:00,1.0,Black,0.30,24.55,0,1